spring:
  application:
    name: org-management

  datasource:
    url: jdbc:mysql://odtT71WYU8ZFPwL.root:53CHX8z7TFG0cZhY@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

services:
  user:
    url: http://localhost:8080/user-service

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

    instances:
      user-service:
        base-config: default

  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

    instances:
      user-service:
        base-config: default
#  jpa:
#    hibernate:
#      ddl-auto: create-only




